### PR TITLE
fileExists should not require write access

### LINKED ISSUE #406: plugin-serverless fails to deploy if package.json owned by another user
If a projects `package.json` is owned by a different user, then the `twilio serverless:deploy` fails to deploy with this error:

```
│ ERROR
│
│ Failed to find package.json file at
│ "/twilio/twilio-test/hello-world/package.json"
```

The `package.json` is readable by the deploying user. We use a shared project repository that is owned by a user other than the deploying user so this is a problem.

You can reproduce this using the `twilio/twilio-cli` docker image and a public project repo I setup. In this case the cloned repo is owned by `root` and if we attempt to deploy as user `node` it fails. If we then chown *only* `package.json` to `node`, then it deploys successfully.

Full transcript of how to reproduce in docker:
```
$ docker run -it --rm twilio/twilio-cli bash
root@12827e427a6b:/twilio# git clone https://github.com/JeremyNorris1234/twilio-test.git
Cloning into 'twilio-test'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 31 (delta 5), reused 31 (delta 5), pack-reused 0
Unpacking objects: 100% (31/31), done.
root@12827e427a6b:/twilio# export TWILIO_ACCOUNT_SID=XXX
root@12827e427a6b:/twilio# export TWILIO_API_SECRET=XXX
root@12827e427a6b:/twilio# export TWILIO_API_KEY=XXX
root@12827e427a6b:/twilio# cd twilio-test/hello-world
root@12827e427a6b:/twilio/twilio-test/hello-world# twilio plugins:install @twilio-labs/plugin-serverless
 » If you’re using autocomplete, you’ll need to run twilio autocomplete after installing a plugin and then open a new terminal window. The CLI needs to re-build its cache.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > @types/is-ci > @types/ci-info@3.1.0: This is a stub types definition. ci-info provides its own type definitions, so you do not need this installed.
warning @twilio-labs/plugin-serverless > @twilio/cli-core > @oclif/plugin-plugins > cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > har-validator@5.1.5: this library is no longer supported
warning "@twilio-labs/plugin-serverless > @twilio/cli-core > @octokit/rest > @octokit/plugin-paginate-rest@2.21.2" has incorrect peer dependency "@octokit/core@>=4".
Installing plugin @twilio-labs/plugin-serverless... installed v3.0.1
root@12827e427a6b:/twilio/twilio-test/hello-world# twilio serverless:deploy --force

Deploying functions & assets to the Twilio Runtime

Username	SK1b006768e808396cbea19ed4fb56365e
Password	OMvB****************************
Service Name	hello-world
Environment	dev
Root Directory	/twilio/twilio-test/hello-world
Dependencies	twilio, @twilio/runtime-handler
Env Variables
Runtime		node14

✔ Serverless project successfully deployed

Deployment Details
Domain: hello-world-5395-dev.twil.io
Service:
   hello-world (ZS170e171148ef566b1ccce7ac18d1be7e)
Environment:
   dev (ZEe512fa7cefdc4d23e503c48c12088fa4)
Build SID:
   ZB5273bd10f76d8a262a0881658c8d2758
Runtime:
   node14
View Live Logs:
   https://www.twilio.com/console/functions/editor/ZS170e171148ef566b1ccce7ac18d1be7e/environment/ZEe512fa7cefdc4d23e503c48c12088fa4
Functions:
   [protected] https://hello-world-5395-dev.twil.io/sms/reply
   https://hello-world-5395-dev.twil.io/hello-world
   https://hello-world-5395-dev.twil.io/private-message
Assets:
   [private] Runtime.getAssets()['/message.js']
   https://hello-world-5395-dev.twil.io/index.html
   https://hello-world-5395-dev.twil.io/style.css
root@12827e427a6b:/twilio/twilio-test/hello-world# id -un
root
root@12827e427a6b:/twilio/twilio-test/hello-world# su node
node@12827e427a6b:/twilio/twilio-test/hello-world$ id -un
node
node@12827e427a6b:/twilio/twilio-test/hello-world$ twilio plugins:install @twilio-labs/plugin-serverless
 » If you’re using autocomplete, you’ll need to run twilio autocomplete after installing a plugin and then open a new terminal window. The CLI needs to re-build its cache.
warning @twilio-labs/plugin-serverless > @twilio/cli-core > @oclif/plugin-plugins > cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @twilio-labs/plugin-serverless > twilio-run > @types/is-ci > @types/ci-info@3.1.0: This is a stub types definition. ci-info provides its own type definitions, so you do not need this installed.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > har-validator@5.1.5: this library is no longer supported
warning "@twilio-labs/plugin-serverless > @twilio/cli-core > @octokit/rest > @octokit/plugin-paginate-rest@2.21.2" has incorrect peer dependency "@octokit/core@>=4".
Installing plugin @twilio-labs/plugin-serverless... installed v3.0.1
node@12827e427a6b:/twilio/twilio-test/hello-world$ twilio serverless:deploy --force

│ ERROR
│
│ Failed to find package.json file at
│ "/twilio/twilio-test/hello-world/package.json"

node@12827e427a6b:/twilio/twilio-test/hello-world$ ls -l package.json
-rw-r--r-- 1 root root 388 Jul 19 13:46 package.json
node@12827e427a6b:/twilio/twilio-test/hello-world$ head -3 package.json
{
  "name": "hello-world",
  "version": "0.0.0",
node@12827e427a6b:/twilio/twilio-test/hello-world$ exit
root@12827e427a6b:/twilio/twilio-test/hello-world# chown node package.json
root@12827e427a6b:/twilio/twilio-test/hello-world# su node
node@12827e427a6b:/twilio/twilio-test/hello-world$ twilio serverless:deploy --force

Deploying functions & assets to the Twilio Runtime

Username	SK1b006768e808396cbea19ed4fb56365e
Password	OMvB****************************
Service Name	hello-world
Environment	dev
Root Directory	/twilio/twilio-test/hello-world
Dependencies	twilio, @twilio/runtime-handler
Env Variables
Runtime		node14

✔ Serverless project successfully deployed

Deployment Details
Domain: hello-world-5395-dev.twil.io
Service:
   hello-world (ZS170e171148ef566b1ccce7ac18d1be7e)
Environment:
   dev (ZEe512fa7cefdc4d23e503c48c12088fa4)
Build SID:
   ZB4a218cac22f619aafbb06235a786e814
Runtime:
   node14
View Live Logs:
   https://www.twilio.com/console/functions/editor/ZS170e171148ef566b1ccce7ac18d1be7e/environment/ZEe512fa7cefdc4d23e503c48c12088fa4
Functions:
   [protected] https://hello-world-5395-dev.twil.io/sms/reply
   https://hello-world-5395-dev.twil.io/hello-world
   https://hello-world-5395-dev.twil.io/private-message
Assets:
   [private] Runtime.getAssets()['/message.js']
   https://hello-world-5395-dev.twil.io/index.html
   https://hello-world-5395-dev.twil.io/style.css
```

### PR DESCRIPTION
**Pull request by rectalogic**
Fixes https://github.com/twilio-labs/serverless-toolkit/issues/406

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by dkundel** [comment]
Thank you for the PR @rectalogic! I think overall this change makes sense but since we are using that method all over the place I'll have to see if this introduces any unexpected side-effects for files where we do expect to have write access. Will potentially have to introduce a second argument here that can be passed to enforce write access. I'll dive into this PR on Friday.

**Comment by dkundel** [comment]
Hey @rectalogic I tried to do some modifications so that I can merge your PR but it looks like I'm hitting some TypeScript issues. I'm trying to debug it and give you an update once it's resolved.

**Comment by rectalogic** [comment]
@dkundel are you referring to https://github.com/twilio-labs/serverless-toolkit/issues/409 - the toolkit is unbuildable?

**Review by dkundel — APPROVED** [review]

**Comment by dkundel** [comment]
Thank you for your contribution @rectalogic and sorry for the delay. I'll be cutting a release next week and will let you know about it

**Pull request merged**
