### PR TITLE
docs: fix typo, executioin -> execution

### PR DESCRIPTION
**Pull request by NReilingh**
Fixed a typo in readme/docs. Not sure how much of this is code-gen'd from other sources, unfortunately, since the two instances I fixed are of the same copy.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by NReilingh** [comment]
Is this build just broken? Pretty sure fixing the spelling of one word isn't gonna be responsible for express not working.

**Comment by philnash** [comment]
Yeah, there seems to be an issue with the build at the moment. I had a play with this and I wasn't sure what was wrong. Will try to sort it out as soon as possible!

**Review by dkundel — APPROVED** [review]

**Comment by dkundel** [comment]
Hey @NReilingh I restructured those files in the meantime in #198 and am closing the PR because it won't be compatible but we appreciate the contribution.

**Comment by NReilingh** [comment]
I resubmitted as #237 since your refactor still retained one of the typos

**Pull request closed without merging**
